//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int Id_Component { get; set; }
        public Nullable<int> Id_Equipment { get; set; }
        public string Cod_Component { get; set; }
        public string Description { get; set; }
        public string Series { get; set; }
        public string Mark { get; set; }
        public string Material { get; set; }
        public string Utility { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
