//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Component = new HashSet<Component>();
            this.FlowDataSensors = new HashSet<FlowDataSensors>();
        }
    
        public int Id_Equipment { get; set; }
        public string Cod_Equipment { get; set; }
        public Nullable<int> Id_Tu { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public string Position { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<Component> Component { get; set; }
        public virtual TreatmentUnit TreatmentUnit { get; set; }
        public virtual ICollection<FlowDataSensors> FlowDataSensors { get; set; }
    }
}
