//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowDataSensors
    {
        public int Id { get; set; }
        public decimal Data_Sensor_PH { get; set; }
        public decimal Data_Sensor_ORP { get; set; }
        public decimal Data_Sensor_DISOLVED_OXYGEN { get; set; }
        public decimal Data_Sensor_CONDUCTIVITY { get; set; }
        public decimal Data_Sensor_WATER_LEVEL { get; set; }
        public Nullable<System.DateTime> Date_Register { get; set; }
        public Nullable<int> Id_Equipment { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
